trigger:
  - main
  - master

variables:
  imageName: software-remittance-tracker-backend
  dockerfilePath: Dockerfile
  tag: $(Build.BuildId)

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Build and Push Docker image
  inputs:
    command: buildAndPush
    containerRegistry: mendixcompras
    repository: $(imageName)
    dockerfile: $(dockerfilePath)
    tags: |
      $(tag)
      latest
